name: flutter_image_compress
description: Compress Pictures. Can effectively reduce the size of the transmission.
repository: https://github.com/fluttercandies/flutter_image_compress
version: 2.1.0

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_image_compress_platform_interface: ^1.0.3
  flutter_image_compress_common:
    git:
      url: https://github.com/nagayukki/flutter_image_compress.git
      path: ./packages/flutter_image_compress_common
      ref: feature/jvm-17
  flutter_image_compress_web:
    git:
      url: https://github.com/nagayukki/flutter_image_compress.git
      path: ./packages/flutter_image_compress_web
      ref: feature/jvm-17
  flutter_image_compress_macos: ^1.0.1

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_image_compress_common
      ios:
        default_package: flutter_image_compress_common
      macos:
        default_package: flutter_image_compress_macos
      web:
        default_package: flutter_image_compress_web